### ISSUE TITLE
Bug: Strange visual bug happening occasionally.

### ISSUE THREAD

**Issue by Dajova** [Drahsid/BetterShadows#2]
Sometimes, the shadows decide to just become a square (rectangle) and the only way to fix it is to disable/enable the plugin. Any thoughts?

![image](https://i.imgur.com/2YXRmdP.png)

**Comment by Drahsid** [comment]
If you can find a way to reproduce this, I will investigate it. I have never seen this, unless the shadowmap resolution is greater than the game supports.

**Comment by Dajova** [comment]
> If you can find a way to reproduce this, I will investigate it. I have never seen this, unless the shadowmap resolution is greater than the game supports.

Maybe because i'm on a ultrawide monitor? There was some other plugins having issues cus of monitor resolution. 3440x1440 in my case.

**Comment by Drahsid** [comment]
I don't have an ultrawide monitor so I can't test this. I'll leave this issue open until we can reproduce it and understand what is going on.

**Comment by Drahsid** [comment]
The latest update allows for increased shadowmap resolution, can you see if that resolves this issue?

**Comment by Drahsid** [comment]
Probably fixed in the latest update. Let me know if this issue reoccurs.
