### ISSUE TITLE
Striped shadows on LOD terrain. 

### ISSUE THREAD

**Issue by TonySherwood** [Drahsid/BetterShadows#3]
Hello, im fairly new to github so bear with me.

ive been having this strange shadow bug ever since i started using Better shadows over a month ago.
I had edited some presets but always made a copy. And settled on just using the default presets, but after a while this bug happened out of nowhere and ive just sort of ignored it hoping it would get fixed at some point.

Ive tried reinstalling the plugin and repairing the game through XIVLauncher but the issue persists even when the plugin is uninstalled. 
Changing cascading settings to low makes it disappear.
i do use a modded FOV as of recently but this had happened prior.
im at a loss as to whats happened.

![Striped shadow LOD](https://github.com/Drahsid/BetterShadows/assets/132406394/f0fbe087-30ad-46e9-8398-d3259f05ed6b)

**Comment by Drahsid** [comment]
The shadowmap at that distance is too low resolution to draw the shadows with high detail. There is nothing I can do to fix that, this is just an issue with your cascade distances.

**Comment by TonySherwood** [comment]
So would i just need to keep editing a custom preset until the issue is resolved? Because i only use the Seamless and Balanced presets that come preinstalled. which had worked before without any weird graphical issues.

**Comment by Drahsid** [comment]
Yeah. If it's still an issue, could be related to #2 which seems to be related to ultrawide monitors.
