### ISSUE TITLE
Reset preset option

### ISSUE THREAD

**Issue by colopatiron** [Drahsid/BetterShadows#4]
An option to reset all presets to default would be nice. You could also add a description for each preset in the actual plugin UI.

**Comment by Drahsid** [comment]
Yeah, I'll implement this. Until the plugin gets updated, if you don't have any presets that you want to keep, but want the defaults, you can delete the plugin's config file and they should get  remade.

**Comment by Drahsid** [comment]
This feature has been added in the latest commit, you should see a "Recover Default Presets" option when the plugin gets updated.
