### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by gucciBane** [Drahsid/BetterShadows#7]
More a question than an issue: is BetterShadows able to fix what's going on on/around these chairs? I'm messing with it and not seeing anything change.

https://gyazo.com/162b8cc143e24fe11f059fb7b82602d5

**Comment by Drahsid** [comment]
This visual effect is related to the near/far shadowmaps, which determine the shadows that are casted by dynamic lights.
I have some commented out code in the codebase which allows me to change the shadowmap resolution of these other maps, but doing that makes the issue way more extreme (the transition from the two shadowmaps is exaggerated and much more noticeable).
I need to do more research on the dynamic lights, and how the near/far shadowmaps are used to be able to adjust this.

**Comment by gucciBane** [comment]
Hm, ok. I'm hoping the 7.0 graphics update fixes it, since it's supposed to
support more light sources. Might not be worth tooling with on your end.

**Comment by Drahsid** [comment]
My reverse engineering on the 7.0 update lead me to reimplementing the related game code for the near/far shadowmaps. You can fix this issue in the latest update by increasing the resolution of the "Distance" shadowmap. Have fun!
